spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: ducthinh1
    url: jdbc:postgresql://localhost:5432/d998qrh3s9j35h
    username: qbtnltcwwdkpsq
    password: b0675ffa3ed16d5819630bec0855d9927f890a8cc4174782374c3cdc5439d886
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
blog:
  title: Thịnh đây
  banner:
    title: Mỗi ngày lớn lên
    content: Khi lớn lên rồi, tôi mới nhận ra mình không còn nhỏ nữa